@startuml
actor Пользователь
box "Система саморазвития" #LightBlue
	participant Интерфейс
	database БД
end box

== Регистрация ==
Пользователь -> Интерфейс: Регистрация
Интерфейс -> БД : Сохранение
|||
Интерфейс <-- БД: Список материалов
activate Интерфейс
Пользователь  -> Интерфейс : Выбор темы
Интерфейс -> БД: Сохранить выбор
deactivate Интерфейс
== Вход ==
Пользователь -> Интерфейс: Вход в ситему
activate Интерфейс
Интерфейс <--  БД : Материалы
Пользователь -> Интерфейс : Изучение
Пользователь -> Интерфейс : Отметка об изучении
Интерфейс -> БД : Сохранение прогресса
deactivate Интерфейс

Интерфейс <-- БД : отображение пргресса \nв календаре
|||
Интерфейс --> Пользователь: Уведомления на email
@enduml